index:
  welcome_message: >
    Avalanche
  personal_photo: "/assets/avalanche.jpg"
  news_highlight_color: 'is-info'
  personal_description: >
    Avalanche is a research portfolio website template based [Jekyll](https://jekyllrb.com) and [bulma](https://bulma.io).
  image_credit: >
    Image Credit: [ling_gigi](https://unsplash.com/@ling_gigi) @ [Unsplash](https://unsplash.com/photos/6fdygx8yHwQ)
  
footnote: Created &amp; maintained by [Zejiang Shen](https://www.szj.io), with [jekyll](https://jekyllrb.com/) and [bulma](http://bulma.io/). The website content is licensed [CC BY NC SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/).